GET http://localhost:3001/api/notes/

###

GET http://localhost:3001/api/notes/1

###

POST http://localhost:3001/api/notes HTTP/1.1
content-type: application/json

{
    "content": "lol",
    "important": false
}

###

PUT http://localhost:3001/api/notes/6121e0cb94e4dc2184f5ae72 HTTP/1.1
content-type: application/json

{
    "content": "CSS is Easy",
    "important": false
}

###

DELETE  http://localhost:3001/api/notes/6121e0cb94e4dc2184f5ae72 HTTP/1.1
